{
    "SerializationMajorVersion": 1,
    "SceneInfo": {
        "ScenePath": "Assets/Scenes/AbilityRoomScene.unity",
        "RootGameObjectInfos": [
            {
                "Name": "Managers",
                "Scripts": [],
                "Children": [
                    {
                        "Name": "FoeHealthDisplayProxy",
                        "Scripts": [
                            {
                                "Name": "FoeHealthDisplayProxy"
                            }
                        ],
                        "Children": []
                    },
                    {
                        "Name": "PlayerProxy",
                        "Scripts": [
                            {
                                "Name": "PlayerProxy"
                            }
                        ],
                        "Children": []
                    }
                ]
            },
            {
                "Name": "Environment",
                "Scripts": [],
                "Children": [
                    {
                        "Name": "Lights",
                        "Scripts": [],
                        "Children": [
                            {
                                "Name": "Directional Light",
                                "Scripts": [],
                                "Children": []
                            }
                        ]
                    },
                    {
                        "Name": "Ground&Walls",
                        "Scripts": [],
                        "Children": [
                            {
                                "Name": "Square",
                                "Scripts": [],
                                "Children": [
                                    {
                                        "Name": "Walls",
                                        "Scripts": [],
                                        "Children": [
                                            {
                                                "Name": "Wall_20x20 (2)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (3)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (4)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (5)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (6)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (7)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (8)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (9)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (10)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (11)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (12)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (13)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (14)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (15)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (16)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (17)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (18)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (19)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (20)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (21)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (22)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        "Name": "Ground",
                                        "Scripts": [],
                                        "Children": [
                                            {
                                                "Name": "Floor_20x20",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (1)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (2)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (3)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (4)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (5)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (6)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (7)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (8)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (9)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (10)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (11)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (12)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (13)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (14)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (15)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (16)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (17)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (18)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (19)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (20)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (21)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (22)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (23)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (24)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (25)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (26)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Floor_20x20 (27)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                "Name": "Corridor",
                                "Scripts": [],
                                "Children": [
                                    {
                                        "Name": "Chunk",
                                        "Scripts": [],
                                        "Children": [
                                            {
                                                "Name": "Floor_20x20 (16)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (1)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Ceilling_20x20 (17)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        "Name": "Chunk (1)",
                                        "Scripts": [],
                                        "Children": [
                                            {
                                                "Name": "Floor_20x20 (16)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (1)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Ceilling_20x20 (17)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        "Name": "Chunk (2)",
                                        "Scripts": [],
                                        "Children": [
                                            {
                                                "Name": "Floor_20x20 (16)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Wall_20x20 (1)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            },
                                            {
                                                "Name": "Ceilling_20x20 (17)",
                                                "Scripts": [],
                                                "Children": [
                                                    {
                                                        "Name": "Floor_10x10",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (1)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (2)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    },
                                                    {
                                                        "Name": "Floor_10x10 (3)",
                                                        "Scripts": [],
                                                        "Children": []
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "Name": "Platforms",
                        "Scripts": [],
                        "Children": [
                            {
                                "Name": "Gen_Ramp_01_snaps002",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (1)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (2)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (3)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (4)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (5)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (6)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (7)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (9)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (10)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (11)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (12)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (13)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (16)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (17)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (18)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (23)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (24)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (22)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (26)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (27)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (28)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (29)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (30)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (31)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (32)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Gen_Ramp_01_snaps002 (1)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (33)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (34)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (35)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (36)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (37)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (38)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (39)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (41)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (42)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (43)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (44)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (45)",
                                "Scripts": [],
                                "Children": []
                            },
                            {
                                "Name": "Deck_FloorCeiling_01_snaps002 (46)",
                                "Scripts": [],
                                "Children": []
                            }
                        ]
                    },
                    {
                        "Name": "Cubes",
                        "Scripts": [],
                        "Children": []
                    },
                    {
                        "Name": "TurretZone",
                        "Scripts": [],
                        "Children": [
                            {
                                "Name": "Wall",
                                "Scripts": [],
                                "Children": [
                                    {
                                        "Name": "Gen_Wall_snaps002",
                                        "Scripts": [],
                                        "Children": []
                                    },
                                    {
                                        "Name": "TurretStateLabel",
                                        "Scripts": [
                                            {
                                                "Name": "SwitchLabel"
                                            },
                                            {
                                                "Name": "TextMeshPro"
                                            }
                                        ],
                                        "Children": []
                                    },
                                    {
                                        "Name": "Switch",
                                        "Scripts": [
                                            {
                                                "Name": "ActivationSwitch"
                                            }
                                        ],
                                        "Children": [
                                            {
                                                "Name": "Cube",
                                                "Scripts": [],
                                                "Children": []
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                "Name": "Entities",
                "Scripts": [],
                "Children": [
                    {
                        "Name": "Foes",
                        "Scripts": [],
                        "Children": [
                            {
                                "Name": "Foe",
                                "Scripts": [
                                    {
                                        "Name": "Foe"
                                    }
                                ],
                                "Children": [
                                    {
                                        "Name": "Capsule",
                                        "Scripts": [],
                                        "Children": []
                                    },
                                    {
                                        "Name": "Sphere",
                                        "Scripts": [],
                                        "Children": []
                                    }
                                ]
                            },
                            {
                                "Name": "MovingFoe",
                                "Scripts": [
                                    {
                                        "Name": "Foe"
                                    },
                                    {
                                        "Name": "SineMove"
                                    }
                                ],
                                "Children": [
                                    {
                                        "Name": "Capsule",
                                        "Scripts": [],
                                        "Children": []
                                    },
                                    {
                                        "Name": "Sphere",
                                        "Scripts": [],
                                        "Children": []
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "Name": "Turret",
                        "Scripts": [
                            {
                                "Name": "TrainingTurret"
                            }
                        ],
                        "Children": [
                            {
                                "Name": "Core",
                                "Scripts": [
                                    {
                                        "Name": "ActivationSwitch"
                                    }
                                ],
                                "Children": []
                            },
                            {
                                "Name": "Cannon",
                                "Scripts": [],
                                "Children": [
                                    {
                                        "Name": "TurretProjectileEmitter",
                                        "Scripts": [
                                            {
                                                "Name": "ProjectileEmitter"
                                            }
                                        ],
                                        "Children": []
                                    },
                                    {
                                        "Name": "Cylinder",
                                        "Scripts": [],
                                        "Children": []
                                    }
                                ]
                            },
                            {
                                "Name": "Base",
                                "Scripts": [],
                                "Children": []
                            }
                        ]
                    }
                ]
            },
            {
                "Name": "Emitters",
                "Scripts": [],
                "Children": [
                    {
                        "Name": "FoeDeathEmitter",
                        "Scripts": [],
                        "Children": []
                    }
                ]
            },
            {
                "Name": "Labels",
                "Scripts": [],
                "Children": [
                    {
                        "Name": "GapWidths",
                        "Scripts": [],
                        "Children": [
                            {
                                "Name": "3m",
                                "Scripts": [
                                    {
                                        "Name": "TextMeshPro"
                                    }
                                ],
                                "Children": []
                            },
                            {
                                "Name": "6m",
                                "Scripts": [
                                    {
                                        "Name": "TextMeshPro"
                                    }
                                ],
                                "Children": []
                            },
                            {
                                "Name": "9m",
                                "Scripts": [
                                    {
                                        "Name": "TextMeshPro"
                                    }
                                ],
                                "Children": []
                            }
                        ]
                    },
                    {
                        "Name": "JumpHeigths",
                        "Scripts": [],
                        "Children": [
                            {
                                "Name": "+2m",
                                "Scripts": [
                                    {
                                        "Name": "TextMeshPro"
                                    }
                                ],
                                "Children": []
                            },
                            {
                                "Name": "+3m",
                                "Scripts": [
                                    {
                                        "Name": "TextMeshPro"
                                    }
                                ],
                                "Children": []
                            },
                            {
                                "Name": "+4m",
                                "Scripts": [
                                    {
                                        "Name": "TextMeshPro"
                                    }
                                ],
                                "Children": []
                            }
                        ]
                    },
                    {
                        "Name": "TestHeigths",
                        "Scripts": [],
                        "Children": [
                            {
                                "Name": "1m",
                                "Scripts": [
                                    {
                                        "Name": "TextMeshPro"
                                    }
                                ],
                                "Children": []
                            },
                            {
                                "Name": "2m",
                                "Scripts": [
                                    {
                                        "Name": "TextMeshPro"
                                    }
                                ],
                                "Children": []
                            },
                            {
                                "Name": "3m",
                                "Scripts": [
                                    {
                                        "Name": "TextMeshPro"
                                    }
                                ],
                                "Children": []
                            },
                            {
                                "Name": "6m",
                                "Scripts": [
                                    {
                                        "Name": "TextMeshPro"
                                    }
                                ],
                                "Children": []
                            },
                            {
                                "Name": "7m",
                                "Scripts": [
                                    {
                                        "Name": "TextMeshPro"
                                    }
                                ],
                                "Children": []
                            },
                            {
                                "Name": "8m",
                                "Scripts": [
                                    {
                                        "Name": "TextMeshPro"
                                    }
                                ],
                                "Children": []
                            },
                            {
                                "Name": "9m",
                                "Scripts": [
                                    {
                                        "Name": "TextMeshPro"
                                    }
                                ],
                                "Children": []
                            },
                            {
                                "Name": "10m",
                                "Scripts": [
                                    {
                                        "Name": "TextMeshPro"
                                    }
                                ],
                                "Children": []
                            },
                            {
                                "Name": "11m",
                                "Scripts": [
                                    {
                                        "Name": "TextMeshPro"
                                    }
                                ],
                                "Children": []
                            }
                        ]
                    }
                ]
            }
        ]
    }
}